name: CI

on:
  push:
    branches:
      - feature/github-actions-heroku

jobs:
  staging-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run test
        run: npm run test
        env:
          CI: true

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Deploy to Heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_STAGING_APP }}.git origin/feature/github-actions-heroku:master
