name: Continuous Deployment

on:
  push:
    branches:
      - master
      - staging

jobs:
  build-and-deploy:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
      HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run test
        run: npm run test
        env:
          CI: true

      - name: Run lint
        run: npm run lint

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP.git
          git push production origin/master:refs/heads/master

      - name: Deploy Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          git remote add staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git
          git push staging origin/staging:refs/heads/master
