name: Continuous Deployment

on:
  push:
    branches:
      - master
      - staging

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run test
        run: npm run test
        env:
          CI: true

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Deploy Production
        if: github.ref == 'refs/heads/master'
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_PRODUCTION_APP }}.git origin/master:master

      - name: Deploy Staging
        if: github.ref == 'refs/heads/staging'
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_STAGING_APP }}.git origin/staging:master
