name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
      - development
      - test-ci-push
jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install node packages
        run: npm install

      - name: Run test
        if: always()
        run: npm run test
        env:
          CI: true

      - name: Run lint
        if: always()
        run: npm run lint

      - name: Run lint 2
        if: always()
        run: npm run lint
